name: Deploy to Lightsail

on:
  push:
    branches:
      - release

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Lightsail
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ${{ secrets.LIGHTSAIL_USERNAME }}
          key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
          port: ${{ secrets.LIGHTSAIL_PORT || 22 }}
          script: |
            # streamlit-financeサービスを停止
            echo "Stopping streamlit-finance service..."
            if ! sudo systemctl stop streamlit-finance; then
              echo "ERROR: Failed to stop streamlit-finance service"
              exit 1
            fi
            echo "Service stopped successfully"

            # /opt/rpaka-financeディレクトリに移動してgit pull
            echo "Pulling latest changes from release branch..."
            cd /opt/rpaka-finance
            if ! git pull origin release; then
              echo "ERROR: Failed to pull from release branch"
              # サービスを再起動してロールバック
              sudo systemctl start streamlit-finance || true
              exit 1
            fi
            echo "Git pull completed successfully"

            # streamlit-financeサービスを起動
            echo "Starting streamlit-finance service..."
            if ! sudo systemctl start streamlit-finance; then
              echo "ERROR: Failed to start streamlit-finance service"
              exit 1
            fi

            # サービスが正常に起動したか確認
            sleep 5
            if ! sudo systemctl is-active --quiet streamlit-finance; then
              echo "ERROR: streamlit-finance service is not running properly"
              sudo systemctl status streamlit-finance
              exit 1
            fi

            echo "Deployment completed successfully"
            echo "Service status:"
            sudo systemctl status streamlit-finance --no-pager
